
dev:
    uv run manage.py runserver

check:
    uv run manage.py check

create_app app:
    uv run manage.py startapp {{app}}

alias mm:=makemigration
#hace una migracion
makemigration app:
    uv run manage.py makemigrations {{app}}

alias m:=migrate
migrate app:
    uv run manage.py migrate {{app}}

alias sh:=shell
#abre una shell
shell:
    uv run manage.py shell
