[project]
name = "supertodo"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.7",
]

[dependency-groups]
dev = [
    "faker>=37.8.0",
    "ipython>=9.6.0",
    "model-bakery>=1.20.5",
    "pytest-django>=4.11.1",
]
