# Generated by Django 5.2.6 on 2025-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='no-slug', max_length=256),
            preserve_default=False,
        ),
    ]
